export const FETCH_TREE_START = 'FETCH_TREE_START'
export const FETCH_TREE_END = 'FETCH_TREE_END'
export const FETCH_TREE_ERR = 'FETCH_TREE_ERR'

export const FETCH_MATCHES_START = 'FETCH_MATCHES_START'
export const FETCH_MATCHES_END = 'FETCH_MATCHES_END'
export const FETCH_MATCHES_ERR = 'FETCH_MATCHES_ERR'

export const FETCH_LAYOUT_START = 'FETCH_LAYOUT_START'
export const FETCH_LAYOUT_END = 'FETCH_LAYOUT_END'
export const FETCH_LAYOUT_ERR = 'FETCH_LAYOUT_ERR'
